# Generated by Django 3.0.3 on 2020-03-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
