#page title
page_title                                : COVID-19 Helpline                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
#ios_app_id                                : #1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                              : _pages/how it works.md                                        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
#playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : COVID-19 Helpline                                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
#app_price                                :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : <b>Helping spread communication about novel virus Covid-19 <br> 
                                            via FREE text messages for everyone.</b>
                                            <br>
                                            

enable_smart_app_banner                   : true                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Anna Tyan                               
your_link                                 : https://behance.net/anna_tyan                     
your_city                                 : St. Louis                                
email_address                             : covid.helpline@gmail.com
facebook_username                         : CovidHelpline                                          
instagram_username                        : covid_helpline
twitter_username                          : covid_helpline
github_username                           : Marwan01/covid-helpline
youtube_username                          : Covid Helpline



# Feature List                            Edit, add or remove features to be presented.
#features                                  :

  #- title                                 : GitHub Pages Jekyll Theme
  #  description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
  #  fontawesome_icon_name                 : magic
    
  #- title                                 : Step 1
  #  description                           : Send any text to +1 (914)268-4399
  #  fontawesome_icon_name                 : mobile

  #- title                                 : Video Support
  #  description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
  #  fontawesome_icon_name                 : play-circle

  #- title                                 : Automatic Icon and Metadata
  #  description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
  #  fontawesome_icon_name                 : sync

  #- title                                 : Easy to Tweak
  #  description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
  #  fontawesome_icon_name                 : adjust
  
  #- title                                 : Step 2
  #  description                           : Choose one of the features from the options pannel you will receive 
  #  fontawesome_icon_name                 : star

  #- title                                 : Smart App Banner
  #  description                           : Display a smart app banner on iOS devices.
  #  fontawesome_icon_name                 : arrow-alt-circle-down

  #- title                                 : Social Links
  #  description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #  fontawesome_icon_name                 : link

  #- title                                 : Step 3
  #  description                           : Receive info. Stay safe. Stay home
  #  fontawesome_icon_name                 : info-circle

  #- title                                 : # New Feature Title
  #  description                           : # New Feature Description
  #  fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.3
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage2.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#363b3d"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown